import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { Login } from "@/components/Login/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ClerkProvider>
				<body className={inter.className}>
					<SignedOut>
						<Login />
					</SignedOut>
					<SignedIn>{children}</SignedIn>
				</body>
			</ClerkProvider>
		</html>
	);
}
