import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.scss";
import { ClerkProvider } from "@clerk/nextjs";
import { ExpenseProvider } from "@/contexts/ExpenseContext";

const sourceSans3 = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={sourceSans3.className}>
					<ExpenseProvider>{children}</ExpenseProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
